#!/bin/bash
#
# DESCRIPTION
#	This script sets up the environment to compile code on pcv or release build machine.
#
# INSTRUCTIONS
#	For developer build:
#		1. Change to root directory of source tree
#		2. Set NLEXTERNALDIR to location where //depot/external is on local disk
#		3. Set NLEXTERNALDIR2 to location where //depot/main/external is on local disk
#		4. Set BUILD_VERSION to a numeric value
#		5. If you are running from CDC or SGDC, you do not have access to s:\.
#			You need to set environment variable BUILD_WITHOUT_S_DRIVE=1 (using 
#			Windows system Advanced Properties).
#		6. If you are running from CDC or SGDC, you need to construct $NLBUILDROOT/xlib 
#			by unzipping buld artifact *-zlib.zip.
#		7. Run 'source ./buildDev'
#		8. Run one of the following command to compile code:
#			ant -f src/build.xml compileOnly
#			ant -f src/build-scripts/project/build.xml build-inquiryCenter
#
#		Example:
#			export NLEXTERNALDIR=c:/hudson/jobs/source_main_external/workspace
#			export NLEXTERNALDIR2=c:/hudson/jobs/source_main_external/workspace
#			export VERSION_BUILD=10001 
#			export BUILD_WITHOUT_S_DRIVE=1
#			<unzip *-zlib.zip into $NLBUILDROOT/xlib>
#			source ./setEnv
#			source ./buildDev
#
#	For manual PCV build:
#		1. Change to root directory of source tree
#		2. Set NLEXTERNALDIR to location where //depot/external is on local disk
#		2. Set NLEXTERNALDIR2 to location where //depot/main/external is on local disk
#		3. Set BUILD_VERSION to a numeric value
#
#		Example:
#			export NLEXTERNALDIR=c:/hudson/jobs/source_external/workspace
#			export NLEXTERNALDIR2=c:/hudson/jobs/source_main_external/workspace
#			export VERSION_BUILD=10001
#			source ./setEnv
#			./buildPcv 
#
#		Script
#			cd $WORKSPACE
#			export NLEXTERNALDIR=c:/hudson/jobs/source_external/workspace
#			export NLEXTERNALDIR2=c:/hudson/jobs/source_main_external/workspace
#			export VERSION_BUILD=${BUILD_NUMBER}
#			source ./setEnv
#			./buildRelease
echo "NextLabs Build Environment Preparation Script (setEnv)"
echo "Specify --help for more information"


#
# Set common environment variables
#

if [ "$ProgramW6432" == "" ]; then
	ENV_OS=x86
	PROGRAM_FILES_X86="C:/Program Files"
else
	ENV_OS=x64
	PROGRAM_FILES_X86="C:/Program Files (x86)"
fi

PROGRAM_FILES_X86_DOS=`cygpath -d "$PROGRAM_FILES_X86"`


#
# Map drives
#
# IMPORTANT: Drive mapping is used to deal with space in directory name such as "Program Files"
# that Cygwin and other programs cannot handle readily.

echo "Drive Mapping Before:"
set -x
net use
subst


[ `subst  | grep -ic O:` -ne 0 ] && subst O: /d
[ `net use  | grep -ic O:` -ne 0 ] && net use O: /d
subst O: "$PROGRAM_FILES_X86_DOS\\Microsoft Visual Studio\\2017\\Professional"

[ `subst  | grep -ic P:` -ne 0 ] && subst P: /d
[ `net use  | grep -ic P:` -ne 0 ] && net use P: /d
subst P: "$PROGRAM_FILES_X86_DOS\\Microsoft Visual Studio\\2017\\Professional\\MSBuild\\15.0\\Bin"

[ `subst  | grep -ic Q:` -ne 0 ] && subst Q: /d
[ `net use  | grep -ic Q:` -ne 0 ] && net use Q: /d
subst Q: "C:\\Program Files\\dotnet"

# When running in Tomcat as SYSTEM user, s:/ is mapped to \\nextlabs.com\share instead of \\nextlabs.com\share\data.
# Drive mapping may be done using subst or net use. It needs to be deleted using the correct command.
# The output from subst may look like the following when mapped using subst. Mapping will not
# be shown if mapped using net use. Similarly, net use does not show mappings done using subst.
#	S:\: => UNC\nextlabs.com\share\data

if [ "$BUILD_WITHOUT_S_DRIVE" == "" ] || [ $BUILD_WITHOUT_S_DRIVE -eq 0 ]; then
	[ `subst | grep -ic S:` -ne 0 ] && subst S: /D
	[ `net use | grep -ic S:` -ne 0 ] && net use S: /D

	net use s: "\\\\nextlabs.com\\share\\data"
fi
set +x

echo "Drive Mapping After:"
set -x
net use
subst
set +x


#
# Set build environment variables
#

if [ "$NLEXTERNALDIR" == "" ]; then
	echo "ERROR: Shell variable NLEXTERNALDIR not set. Exiting..."
	exit 1
fi

if [ "$NLEXTERNALDIR2" == "" ]; then
	echo "ERROR: Shell variable NLEXTERNALDIR2 not set. Exiting..."
	exit 1
fi

export NLBUILDROOT=$(cygpath -m $(pwd))

alias dev='cd $NLBUILDROOT'
alias inst='cd $NLBUILDROOT/install'
alias prod='cd $NLBUILDROOT/prod'


#
# Print message
#

echo ""
echo "-------------------------------------------------------------------------"
echo "IMPORTANT: You must source this script in a Bash shell to setup the environment."
echo "Invoking ./setEnv will create a new child shell process and the script will"
echo "run in the child process. Changes to the environment is limited to the child"
echo "process, parent process is not affected. The command you should run is:"
echo "  source ./setEnv"
echo "-------------------------------------------------------------------------"